name: vox.Force

options:
  bundleIdPrefix: com.matttalafous

settings:
  base:
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    ARCHS: arm64
    ONLY_ACTIVE_ARCH: NO

configs:
  Debug: debug
  Release: release

targets:
  vox.Force:
    type: application
    platform: iOS
    deploymentTarget: "15.0"

    sources:
      - path: vox.Force
        includes:
          - "**/*.swift"
          - "**/*.metal"
        excludes:
          - "Preview Content/**"
        buildPhase: sources

      - path: vox.Force/Base.lproj
        buildPhase: resources

      - path: vox.Force/Models
        buildPhase: resources

    info:
      path: vox.Force/Info.plist

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.matttalafous.voxForce
        PRODUCT_NAME: vox.Force
        TARGETED_DEVICE_FAMILY: "1,2"

        ARCHS: arm64
        ONLY_ACTIVE_ARCH: NO

        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""

        ENABLE_BITCODE: NO

    scheme:
      gatherCoverageData: false
